name: CI-WORKFLOW
on: push    

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v7
        
      - name: installing nodejs
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: build
        run: npm install

      - name: test
        run: npm test

      - name: deploy
        run: echo "my code is deployed" 

      
